task: 4k4d
gpus: [0]
exp_name: 'r4k4d_demo'
scene: 'renbody'

# module path
train_dataset_module: lib.datasets.r4K4D.renbody_video
test_dataset_module: lib.datasets.r4K4D.renbody_video
network_module: lib.networks.r4K4D.network
evaluator_module: lib.evaluators.r4K4D
loss_module: lib.train.losses.r4K4D_reg

# TODO[future]: add visualizer
#visualizer_module: lib.visualizers.r4K4D
task_arg:
    dim_time : 1
    camera_use: 48

train_dataset:
    data_root: 'data/renbody/0013_01'
    split: 'train'
    nearset_N_views: 4
    input_ratio: 1.0


test_dataset:
    data_root: 'data/renbody/0013_01'
    split: 'test'

model_cfg:
    skip_loading_points: False
    pcds_dir: 'data/renbody/0013_01/surfs'
    network_encoder:
        xyzt_encoder_cfg:
            type: 'hexplane'
            n_levels: 1
            n_features_per_level: 32
        ibr_encoder_cfg:
            type: 'geo_ibr'
            n_levels: 1
    IBR_regressor:
        type: 'geo_ibr'
        sh_deg: 3
        in_dim: 192
        src_dim: 11
        out_dim: 3
        width: 64
        depth: 1
    geo_linear:
        width: 64
        depth: 2
        out_dim: 2 # radius, density
    K_points: 15

train:
    lr: 5e-3
    num_workers: 1
    batch_size: 1
    lmbda1: 0.1
    lmbda2: 0.1



ep_iter: 50
eval_ep: 10
save_latest_ep: 1
log_interval: 10